/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.iesalquerias.view;

import es.iesalquerias.model.Model;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
/**
 *
 * @author lopas
 */
public class View extends javax.swing.JFrame {

    Model model = new Model();
    String functions = "-+.*/";
    String vCharacters = "0123456789-+.*/";

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    private void presenterModifiesModel(Double n1, Double n2, String operacion){ 
        model.setN1(n1);
        model.setN2(n2);
        model.setOperacion(operacion);
    }
    
    private void presenterCalcModel(){ 
        if ("+".equals(model.getOperacion())){
            model.setRes(model.getN1() + model.getN2());
        }
        if ("-".equals(model.getOperacion())){
            model.setRes(model.getN1() - model.getN2());
        }
        if ("/".equals(model.getOperacion())){
            model.setRes(model.getN1() / model.getN2());
        }
        if ("*".equals(model.getOperacion())){
            model.setRes(model.getN1() * model.getN2());
        }
        
    }
       
    private void presenterUpdateTextf(){
        jTFProcess.setText(model.getRes() + "");
    }
    
    private void presenterCheckOp(){ 
        if(jTFProcess.getText().split("-").length > 1){
            String[] datos = jTFProcess.getText().split("-");
            Double n1 = Double.valueOf(datos[0]);
            Double n2 = Double.valueOf(datos[1]);
            presenterModifiesModel(n1,n2,"-");
            presenterCalcModel();
            presenterUpdateTextf();
        }
        if(jTFProcess.getText().split("\\+").length > 1){
            String[] datos = jTFProcess.getText().split("\\+");
            Double n1 = Double.valueOf(datos[0]);
            Double n2 = Double.valueOf(datos[1]);
            presenterModifiesModel(n1,n2,"+");
            presenterCalcModel();
            presenterUpdateTextf();
        }
        if(jTFProcess.getText().split("\\*").length > 1){
            String[] datos = jTFProcess.getText().split("\\*");
            Double n1 = Double.valueOf(datos[0]);
            Double n2 = Double.valueOf(datos[1]);
            presenterModifiesModel(n1,n2,"*");
            presenterCalcModel();
            presenterUpdateTextf();
        }
        if(jTFProcess.getText().split("/").length > 1){
            String[] datos = jTFProcess.getText().split("/");
            Double n1 = Double.valueOf(datos[0]);
            Double n2 = Double.valueOf(datos[1]);
            presenterModifiesModel(n1,n2,"/");
            presenterCalcModel();
            presenterUpdateTextf();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jTFProcess = new javax.swing.JTextField();
        jBtEight = new javax.swing.JButton();
        jBtDivide = new javax.swing.JButton();
        jBtSeven = new javax.swing.JButton();
        jBtNine = new javax.swing.JButton();
        jBtMultiply = new javax.swing.JButton();
        jBtSix = new javax.swing.JButton();
        jBtFive = new javax.swing.JButton();
        jBtClear = new javax.swing.JButton();
        jBtPlus = new javax.swing.JButton();
        jBtComma = new javax.swing.JButton();
        jBtFour = new javax.swing.JButton();
        jBtSubtraction = new javax.swing.JButton();
        jBtThree = new javax.swing.JButton();
        jBtTwo = new javax.swing.JButton();
        jBtOne = new javax.swing.JButton();
        jBtZero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jTFProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFProcessActionPerformed(evt);
            }
        });
        jTFProcess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFProcessKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 211;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(31, 14, 0, 12);
        jPanel2.add(jTFProcess, gridBagConstraints);

        jBtEight.setText("8");
        jBtEight.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEightActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(jBtEight, gridBagConstraints);

        jBtDivide.setText("/");
        jBtDivide.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDivideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 10);
        jPanel2.add(jBtDivide, gridBagConstraints);

        jBtSeven.setText("7");
        jBtSeven.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSevenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel2.add(jBtSeven, gridBagConstraints);

        jBtNine.setText("9");
        jBtNine.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(jBtNine, gridBagConstraints);

        jBtMultiply.setText("*");
        jBtMultiply.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtMultiplyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 10);
        jPanel2.add(jBtMultiply, gridBagConstraints);

        jBtSix.setText("6");
        jBtSix.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSixActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(jBtSix, gridBagConstraints);

        jBtFive.setText("5");
        jBtFive.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFiveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(jBtFive, gridBagConstraints);

        jBtClear.setText("C");
        jBtClear.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 11, 0);
        jPanel2.add(jBtClear, gridBagConstraints);

        jBtPlus.setText("+");
        jBtPlus.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 11, 10);
        jPanel2.add(jBtPlus, gridBagConstraints);

        jBtComma.setText(".");
        jBtComma.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCommaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 11, 0);
        jPanel2.add(jBtComma, gridBagConstraints);

        jBtFour.setText("4");
        jBtFour.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFourActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel2.add(jBtFour, gridBagConstraints);

        jBtSubtraction.setText("-");
        jBtSubtraction.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtSubtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSubtractionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 10);
        jPanel2.add(jBtSubtraction, gridBagConstraints);

        jBtThree.setText("3");
        jBtThree.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtThreeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(jBtThree, gridBagConstraints);

        jBtTwo.setText("2");
        jBtTwo.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtTwoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(jBtTwo, gridBagConstraints);

        jBtOne.setText("1");
        jBtOne.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtOneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel2.add(jBtOne, gridBagConstraints);

        jBtZero.setText("0");
        jBtZero.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtZeroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 11, 0);
        jPanel2.add(jBtZero, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFProcessActionPerformed

    private void jBtSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSevenActionPerformed
        jTFProcess.setText(jTFProcess.getText() +  "7");
        presenterCheckOp();
    }//GEN-LAST:event_jBtSevenActionPerformed

    private void jBtEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEightActionPerformed
        jTFProcess.setText(jTFProcess.getText() +  "8");
        presenterCheckOp();
    }//GEN-LAST:event_jBtEightActionPerformed

    private void jBtNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNineActionPerformed
        jTFProcess.setText(jTFProcess.getText() +  "9");
        presenterCheckOp();
    }//GEN-LAST:event_jBtNineActionPerformed

    private void jBtDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDivideActionPerformed
        String txt = jTFProcess.getText();
        char uC = txt.charAt(txt.length() - 1);
        if (!functions.contains(uC + "")){
            jTFProcess.setText(jTFProcess.getText() +  "/");
        }
    }//GEN-LAST:event_jBtDivideActionPerformed

    private void jBtFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFourActionPerformed
        jTFProcess.setText(jTFProcess.getText() +  "4");
        presenterCheckOp();
    }//GEN-LAST:event_jBtFourActionPerformed

    private void jBtFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFiveActionPerformed
        jTFProcess.setText(jTFProcess.getText() +  "5");
        presenterCheckOp();
    }//GEN-LAST:event_jBtFiveActionPerformed

    private void jBtSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSixActionPerformed
        jTFProcess.setText(jTFProcess.getText() +  "6");
        presenterCheckOp();
    }//GEN-LAST:event_jBtSixActionPerformed

    private void jBtMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtMultiplyActionPerformed
        String txt = jTFProcess.getText();
        char uC = txt.charAt(txt.length() - 1);
        if (!functions.contains(uC + "")){
            jTFProcess.setText(jTFProcess.getText() +  "*");
        }
    }//GEN-LAST:event_jBtMultiplyActionPerformed

    private void jBtOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtOneActionPerformed
        jTFProcess.setText(jTFProcess.getText() +  "1");
        presenterCheckOp();
    }//GEN-LAST:event_jBtOneActionPerformed

    private void jBtTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtTwoActionPerformed
        jTFProcess.setText(jTFProcess.getText() +  "2");
        presenterCheckOp();
    }//GEN-LAST:event_jBtTwoActionPerformed

    private void jBtThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtThreeActionPerformed
        jTFProcess.setText(jTFProcess.getText() +  "3");
        presenterCheckOp();
    }//GEN-LAST:event_jBtThreeActionPerformed

    private void jBtSubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSubtractionActionPerformed
        String txt = jTFProcess.getText();
        char uC = txt.charAt(txt.length() - 1);
        if (!functions.contains(uC + "")){
            jTFProcess.setText(jTFProcess.getText() +  "-");
        }
    }//GEN-LAST:event_jBtSubtractionActionPerformed

    private void jBtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtClearActionPerformed
        jTFProcess.setText("");
    }//GEN-LAST:event_jBtClearActionPerformed

    private void jBtZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtZeroActionPerformed
        jTFProcess.setText(jTFProcess.getText() +  "0");
        presenterCheckOp();
    }//GEN-LAST:event_jBtZeroActionPerformed

    private void jBtCommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCommaActionPerformed
        String txt = jTFProcess.getText();
        char uC = txt.charAt(txt.length() - 1);
        if (!functions.contains(uC + "")){
            jTFProcess.setText(jTFProcess.getText() +  ".");
        }
    }//GEN-LAST:event_jBtCommaActionPerformed

    private void jBtPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPlusActionPerformed
        String txt = jTFProcess.getText();
        char uC = txt.charAt(txt.length() - 1);
        if (!functions.contains(uC + "")){
            jTFProcess.setText(jTFProcess.getText() +  "+");
        }
    }//GEN-LAST:event_jBtPlusActionPerformed

    private void jTFProcessKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFProcessKeyTyped
        
    }//GEN-LAST:event_jTFProcessKeyTyped

    private void registrerKeyBindings(JButton button,
            KeyStroke key, String mapKey) {
        button.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(key, mapKey);
        button.getActionMap().put(mapKey, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                button.doClick();
            }
        });
    }
    
    private void generarKeyBindigs() {
        registrerKeyBindings(jBtZero,
                KeyStroke.getKeyStroke("0"), "0");
        registrerKeyBindings(jBtZero,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_NUMPAD0, 0), "0");
        registrerKeyBindings(jBtOne,
                KeyStroke.getKeyStroke("1"), "1");
        registrerKeyBindings(jBtOne,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_NUMPAD1, 0), "1");
        registrerKeyBindings(jBtTwo,
                KeyStroke.getKeyStroke("2"), "2");
        registrerKeyBindings(jBtTwo,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_NUMPAD2, 0), "2");
        registrerKeyBindings(jBtThree,
                KeyStroke.getKeyStroke("3"), "3");
        registrerKeyBindings(jBtThree,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_NUMPAD3, 0), "3");
        registrerKeyBindings(jBtFour,
                KeyStroke.getKeyStroke("4"), "4");
        registrerKeyBindings(jBtFour,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_NUMPAD4, 0), "4");
        registrerKeyBindings(jBtFive,
                KeyStroke.getKeyStroke("5"), "5");
        registrerKeyBindings(jBtFive,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_NUMPAD5, 0), "5");
        registrerKeyBindings(jBtSix,
                KeyStroke.getKeyStroke("6"), "6");
        registrerKeyBindings(jBtSix,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_NUMPAD6, 0), "6");
        registrerKeyBindings(jBtSeven,
                KeyStroke.getKeyStroke("7"), "7");
        registrerKeyBindings(jBtSeven,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_NUMPAD7, 0), "7");
        registrerKeyBindings(jBtEight,
                KeyStroke.getKeyStroke("8"), "8");
        registrerKeyBindings(jBtEight,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_NUMPAD8, 0), "8");
        registrerKeyBindings(jBtNine,
                KeyStroke.getKeyStroke("9"), "9");
        registrerKeyBindings(jBtNine,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_NUMPAD9, 0), "9");
        registrerKeyBindings(jBtPlus,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_ADD, 0), "+");
        registrerKeyBindings(jBtPlus,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_PLUS, 0), "+");
        registrerKeyBindings(jBtSubtraction,
                KeyStroke.getKeyStroke(KeyEvent.VK_SUBTRACT, 0), "-");
        registrerKeyBindings(jBtSubtraction,
                KeyStroke.getKeyStroke(KeyEvent.VK_MINUS, 0), "-");
        registrerKeyBindings(jBtMultiply,
                KeyStroke.getKeyStroke(KeyEvent.VK_PLUS,
                        InputEvent.SHIFT_DOWN_MASK), "*");
        registrerKeyBindings(jBtMultiply,
                KeyStroke.getKeyStroke(KeyEvent.VK_MULTIPLY, 0), "*");
        registrerKeyBindings(jBtMultiply,
                KeyStroke.getKeyStroke(KeyEvent.VK_ASTERISK, 0), "*");
        registrerKeyBindings(jBtDivide,
                KeyStroke.getKeyStroke(KeyEvent.VK_7,
                        InputEvent.SHIFT_DOWN_MASK), "/");
        registrerKeyBindings(jBtDivide,
                KeyStroke.getKeyStroke(KeyEvent.VK_DIVIDE, 0), "/");
        registrerKeyBindings(jBtDivide,
                KeyStroke.getKeyStroke(KeyEvent.VK_SLASH, 0), "/");
        registrerKeyBindings(jBtComma,
                KeyStroke.getKeyStroke(
                        KeyEvent.VK_DECIMAL, 0), ".");
        registrerKeyBindings(jBtComma,
                KeyStroke.getKeyStroke(KeyEvent.VK_PERIOD, 0),
                ".");

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtClear;
    private javax.swing.JButton jBtComma;
    private javax.swing.JButton jBtDivide;
    private javax.swing.JButton jBtEight;
    private javax.swing.JButton jBtFive;
    private javax.swing.JButton jBtFour;
    private javax.swing.JButton jBtMultiply;
    private javax.swing.JButton jBtNine;
    private javax.swing.JButton jBtOne;
    private javax.swing.JButton jBtPlus;
    private javax.swing.JButton jBtSeven;
    private javax.swing.JButton jBtSix;
    private javax.swing.JButton jBtSubtraction;
    private javax.swing.JButton jBtThree;
    private javax.swing.JButton jBtTwo;
    private javax.swing.JButton jBtZero;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFProcess;
    // End of variables declaration//GEN-END:variables
}
